# Generated by Django 3.2.9 on 2021-12-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='name',
            new_name='branch_name',
        ),
    ]
