# Generated by Django 3.2.9 on 2021-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_branches_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='branches',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
